package toolwrap

import (
	"strings"
	"testing"
)

func lineCount(s string) int { return strings.Count(s, "\n") }

func callCount(s string) int { return strings.Count(s, "__cadr_trace(") }

func TestInstrumentSource(t *testing.T) {
	root := "/proj"
	path := "/proj/pkg/app.go"

	tests := []struct {
		name      string
		src       string
		wantCalls []string // exact __cadr_trace call prefixes
		wantCount int
		wantPkg   string
	}{
		{
			name: "plain function",
			src:  "package app\n\nfunc Add(a, b int) int {\n\treturn a + b\n}\n",
			wantCalls: []string{
				`__cadr_trace("Add","/proj/pkg/app.go",3);`,
			},
			wantCount: 1,
			wantPkg:   "app",
		},
		{
			name: "methods value pointer and generic receiver",
			src:  "package app\n\ntype Stack[T any] struct{}\n\nfunc (s Stack[T]) Len() int { return 0 }\n\nfunc (s *Stack[T]) Push(v T) {}\n\nfunc (s *Stack[T]) pop() {}\n",
			wantCalls: []string{
				`__cadr_trace("Stack.Len","/proj/pkg/app.go",5);`,
				`__cadr_trace("Stack.Push","/proj/pkg/app.go",7);`,
				`__cadr_trace("Stack.pop","/proj/pkg/app.go",9);`,
			},
			wantCount: 3,
			wantPkg:   "app",
		},
		{
			name: "multi-line signature",
			src:  "package app\n\nfunc Long(\n\ta int,\n\tb int,\n) int {\n\treturn a + b\n}\n",
			wantCalls: []string{
				`__cadr_trace("Long","/proj/pkg/app.go",3);`,
			},
			wantCount: 1,
			wantPkg:   "app",
		},
		{
			name: "one-line and empty bodies",
			src:  "package app\n\nfunc One() { One() }\n\nfunc Empty() {}\n",
			wantCalls: []string{
				`__cadr_trace("One","/proj/pkg/app.go",3);`,
				`__cadr_trace("Empty","/proj/pkg/app.go",5);`,
			},
			wantCount: 2,
			wantPkg:   "app",
		},
		{
			name: "init underscore and bodyless skipped",
			src:  "package app\n\nfunc init() {}\n\nfunc _() {}\n\nfunc Asm()\n\nfunc Keep() {}\n",
			wantCalls: []string{
				`__cadr_trace("Keep","/proj/pkg/app.go",9);`,
			},
			wantCount: 1,
			wantPkg:   "app",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			out, n, pkg, err := instrumentSource(path, []byte(tt.src), root)
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if n != tt.wantCount {
				t.Fatalf("count = %d, want %d\n%s", n, tt.wantCount, out)
			}
			if pkg != tt.wantPkg {
				t.Fatalf("pkg = %q, want %q", pkg, tt.wantPkg)
			}
			if got := lineCount(string(out)); got != lineCount(tt.src) {
				t.Fatalf("line count changed: %d -> %d\n%s", lineCount(tt.src), got, out)
			}
			if got := callCount(string(out)); got != tt.wantCount {
				t.Fatalf("call count = %d, want %d\n%s", got, tt.wantCount, out)
			}
			for _, want := range tt.wantCalls {
				if !strings.Contains(string(out), want) {
					t.Errorf("missing %q in:\n%s", want, out)
				}
			}
			// The call must land immediately after the opening brace.
			for _, line := range strings.Split(string(out), "\n") {
				if i := strings.Index(line, "__cadr_trace("); i > 0 {
					if !strings.Contains(line[:i], "{") {
						t.Errorf("trace call not immediately after brace: %q", line)
					}
				}
			}
		})
	}
}

func TestInstrumentSourceSkips(t *testing.T) {
	src := []byte("package app\n\nfunc Keep() {}\n")
	cases := []struct {
		name string
		path string
		root string
		src  []byte
	}{
		{"outside root", "/other/app.go", "/proj", src},
		{"vendor", "/proj/vendor/lib/app.go", "/proj", src},
		{"cadr dir", "/proj/.cadr/x.go", "/proj", src},
		{"runtime file", "/proj/__cadr_runtime.go", "/proj", src},
		{
			"generated",
			"/proj/app.go",
			"/proj",
			[]byte("// Code generated by tool. DO NOT EDIT.\n\npackage app\n\nfunc Keep() {}\n"),
		},
	}
	for _, tt := range cases {
		t.Run(tt.name, func(t *testing.T) {
			out, n, _, err := instrumentSource(tt.path, tt.src, tt.root)
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if n != 0 || out != nil {
				t.Fatalf("expected skip, got n=%d out=%q", n, out)
			}
		})
	}
}

func TestSplitArgs(t *testing.T) {
	args := []string{"-o", "/tmp/x.a", "-trimpath", "/tmp/b001=>", "-p", "main", "-importcfg", "/tmp/importcfg", "-pack", "/proj/main.go", "/proj/util.go"}
	flags, files := splitArgs(args)
	if len(files) != 2 || files[0] != "/proj/main.go" || files[1] != "/proj/util.go" {
		t.Fatalf("files = %v", files)
	}
	if len(flags) != 9 || flags[len(flags)-1] != "-pack" {
		t.Fatalf("flags = %v", flags)
	}

	flags, files = splitArgs([]string{"-V=full"})
	if len(files) != 0 || len(flags) != 1 {
		t.Fatalf("probe: flags=%v files=%v", flags, files)
	}
}

func TestAddTrimpathMerges(t *testing.T) {
	got := addTrimpath([]string{"-importcfg", "/tmp/cfg", "-trimpath", "/tmp/b001=>"}, []string{"/tmp/a.go=>/proj/a.go"})
	if got[3] != "/tmp/b001=>;/tmp/a.go=>/proj/a.go" {
		t.Fatalf("merged trimpath = %q", got[3])
	}

	got = addTrimpath([]string{"-o", "/tmp/x.a"}, []string{"/tmp/a.go=>/proj/a.go"})
	if got[len(got)-2] != "-trimpath" || got[len(got)-1] != "/tmp/a.go=>/proj/a.go" {
		t.Fatalf("appended trimpath = %v", got)
	}

	got = addTrimpath([]string{"-trimpath=/tmp/b001=>"}, []string{"/tmp/a.go=>/proj/a.go"})
	if got[0] != "-trimpath=/tmp/b001=>;/tmp/a.go=>/proj/a.go" {
		t.Fatalf("equals-form trimpath = %q", got[0])
	}
}
