package toolwrap

import (
	"crypto/sha256"
	"encoding/hex"
)

// instrumentVersion must be bumped whenever the injected runtime or the
// instrumentation strategy changes. It is folded into the isolated GOCACHE
// directory name so that stale instrumented archives are never reused after a
// cadr upgrade.
const instrumentVersion = "1"

// runtimeBody is the source of the self-contained tracing runtime that cadr
// injects into every package it instruments. It uses only the standard library
// and declares every symbol with a __cadr_ prefix so it cannot collide with
// user code.
//
// It writes newline-delimited JSON matching tracer.Event to the CADR_SOCKET
// unix socket (or CADR_TCP) and falls back to stderr when no listener is
// reachable, mirroring internal/agents/py_trace.py.
const runtimeBody = `
import (
	"net"
	"os"
	"sync"
	"sync/atomic"
	"time"
)

var (
	__cadr_once  sync.Once
	__cadr_ch    chan []byte
	__cadr_live  int32
	__cadr_local int32
	__cadr_wmu   sync.Mutex
)

func __cadr_init() {
	if os.Getenv("CADR_LOCAL_ONLY") == "1" {
		atomic.StoreInt32(&__cadr_local, 1)
		return
	}
	__cadr_ch = make(chan []byte, 8192)
	go __cadr_sender()
}

func __cadr_trace(fn, file string, line int) {
	__cadr_once.Do(__cadr_init)
	msg := __cadr_line(fn, file, line)
	if atomic.LoadInt32(&__cadr_local) == 1 {
		__cadr_write(msg)
		return
	}
	select {
	case __cadr_ch <- msg:
	default:
	}
	if atomic.LoadInt32(&__cadr_live) == 0 {
		__cadr_write(msg)
	}
}

func __cadr_write(msg []byte) {
	__cadr_wmu.Lock()
	_, _ = os.Stderr.Write(msg)
	__cadr_wmu.Unlock()
}

func __cadr_sender() {
	for {
		var conn net.Conn
		var err error
		if sock := os.Getenv("CADR_SOCKET"); sock != "" {
			conn, err = net.Dial("unix", sock)
		} else {
			port := os.Getenv("CADR_TCP")
			if port == "" {
				port = "9876"
			}
			conn, err = net.Dial("tcp", "127.0.0.1:"+port)
		}
		if err != nil {
			atomic.StoreInt32(&__cadr_live, 0)
			time.Sleep(200 * time.Millisecond)
			continue
		}
		atomic.StoreInt32(&__cadr_live, 1)
		for msg := range __cadr_ch {
			if _, err := conn.Write(msg); err != nil {
				atomic.StoreInt32(&__cadr_live, 0)
				_ = conn.Close()
				break
			}
		}
	}
}

func __cadr_line(fn, file string, line int) []byte {
	b := make([]byte, 0, len(fn)+len(file)+48)
	b = append(b, "{\"fn\":\""...)
	b = __cadr_esc(b, fn)
	b = append(b, "\",\"file\":\""...)
	b = __cadr_esc(b, file)
	b = append(b, "\",\"line\":"...)
	b = __cadr_itoa(b, line)
	b = append(b, ",\"args\":{}}\n"...)
	return b
}

func __cadr_esc(b []byte, s string) []byte {
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch c {
		case '"':
			b = append(b, '\\', '"')
		case '\\':
			b = append(b, '\\', '\\')
		case '\n':
			b = append(b, '\\', 'n')
		case '\r':
			b = append(b, '\\', 'r')
		case '\t':
			b = append(b, '\\', 't')
		default:
			if c < 0x20 {
				const hex = "0123456789abcdef"
				b = append(b, '\\', 'u', '0', '0', hex[c>>4], hex[c&0x0f])
			} else {
				b = append(b, c)
			}
		}
	}
	return b
}

func __cadr_itoa(b []byte, n int) []byte {
	if n == 0 {
		return append(b, '0')
	}
	if n < 0 {
		b = append(b, '-')
		n = -n
	}
	var tmp [20]byte
	i := len(tmp)
	for n > 0 {
		i--
		tmp[i] = byte('0' + n%10)
		n /= 10
	}
	return append(b, tmp[i:]...)
}
`

// runtimeSource returns the full source of the injected runtime file for the
// given package name.
func runtimeSource(pkg string) string {
	return "// Code generated by cadr. DO NOT EDIT.\n\npackage " + pkg + "\n" + runtimeBody
}

// CacheKey returns a short, stable fingerprint of the injected runtime. It is
// used to isolate the Go build cache per instrumentation version.
func CacheKey() string {
	h := sha256.Sum256([]byte(instrumentVersion + runtimeBody))
	return hex.EncodeToString(h[:])[:12]
}
